### ISSUE TITLE
Native dependency missing

### ISSUE THREAD

**Issue by Krzyjan** [nacular/doodle#30] opened 2022-02-02 05:43 UTC
Using the sample code in the Application section of the Guide, a pure JVM Kotlin build script and the latest Intellij IDEA (IntelliJ IDEA Community Edition 2021.3.2) I get the following error when attempting to run the main class from Intellij:

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.jetbrains.skiko.SkiaWindow$1.invoke(SkiaWindow.kt:7)
	at org.jetbrains.skiko.SkiaWindow$1.invoke(SkiaWindow.kt:7)
	at org.jetbrains.skiko.SkiaWindow.<init>(SkiaWindow.kt:9)
	at org.jetbrains.skiko.SkiaWindow.<init>(SkiaWindow.kt:5)
	at io.nacular.doodle.application.ApplicationHolderImpl.<init>(Application.kt:86)
	at io.nacular.doodle.application.ApplicationHolderImpl.<init>(Application.kt:72)
	at io.nacular.doodle.application.ApplicationHolderImpl$Companion.invoke(Application.kt:168)
	at io.nacular.doodle.application.ApplicationKt.createApplication(Application.kt:70)
	at MainKt.main(Main.kt:12)
	at MainKt.main(Main.kt)
Caused by: org.jetbrains.skiko.LibraryLoadException: Cannot find skiko-windows-x64.dll.sha256, proper native dependency missing.
	at org.jetbrains.skiko.Library.load(Library.kt:72)
	at org.jetbrains.skiko.SkiaLayer.<clinit>(SkiaLayer.kt:25)
	... 10 more

Reinstalling Intellij has not fixed the problem.

**Comment by pusolito** [comment] 2022-02-02 14:50
Thanks for filing an issue. This came up in #28 as well. The root cause is a missing dependency for 0.6.x and earlier. The fix is coming in the next release: 0.7.0. It will require apps to specify a platform specific dependency to the desktop library.

You can work around this in the meantime by doing what the tutorials [do](https://github.com/nacular/doodle-tutorials/blob/e1c71080e70af050326153bd4dd3d5c8a8b783ec/CalculatorRunner/build.gradle.kts#L37). They explicitly pull in the skiko version in their dependency list.

Please keep this issue open for others to see the context.

**Comment by Krzyjan** [comment] 2022-02-03 06:23
Thanks for that, Nicholas. Adding this Kotlin code to kotlin.dependencies in your build.gradle.kts fixes the problem:

`        // Work-around for https://github.com/nacular/doodle/issues/28
        val osName = System.getProperty("os.name")
        val targetOs = when {
            osName == "Mac OS X"       -> "macos"
            osName.startsWith("Win"  ) -> "windows"
            osName.startsWith("Linux") -> "linux"
            else                       -> error("Unsupported OS: $osName")
        }

        val osArch = System.getProperty("os.arch")
        val targetArch = when (osArch) {
            "x86_64", "amd64" -> "x64"
            "aarch64"         -> "arm64"
            else              -> error("Unsupported arch: $osArch")
        }

        val target = "${targetOs}-${targetArch}"

        implementation("org.jetbrains.skiko:skiko-jvm-runtime-$target:0.4.16")
`

**Comment by pusolito** [comment] 2022-02-25 16:19
Now fixed with 0.7.0.

**Closed by pusolito** 2022-02-25 16:19 UTC
